### ISSUE TITLE
Look into database setup

### ISSUE THREAD

**Issue by eugenetriguba** [eugenetriguba/augie-health-admin-menu#1]
This will likely be sqlite3 since it can be packaged with the application then. See if we can leverage an ORM & migrations. Possibly useful: https://github.com/sjmelia/electron-boilerplate-sqlite

**Comment by eugenetriguba** [comment]
Maybe give this a look? https://sequelize.readthedocs.io/en/v3/

**Comment by subiedaveee** [comment]
I'll definitely look into that, it seems pretty promising if I can get it to converse well with the Google Calendar data formats. As far as a database goes do we plan on creating one with a host outside of the local network or will it be a local network database that we'll have to create on our own? I'm not too sure what we decided on ultimately doing in class.

**Comment by eugenetriguba** [comment]
A sqlite database is just a binary file. So the database would just be a file that is packaged with the application. I don't see why you'd need to look into conversing with google calendar for the database layout though. Maybe I'm missing something there so feel free to clarify if I am. We'll be pulling in the data from google calendar through the their API on the front end and can format it in anyway we need to before storing it into the database.

**Comment by eugenetriguba** [comment]
I'm going to start looking into this as well since we're going to need the database for most things moving forward

**Comment by eugenetriguba** [comment]
There is a bookings and waitlists table that you can create by using the sequelize cli and running `sequelize db:migrate` which will create both tables and the sqlite3 database file in the `app/database/` folder. You can use something like https://sqlitebrowser.org/ to view the database.
